python_app(
  name='analytics',
  binary='src/py/example/airflow/main',
  bundles=[
    bundle(fileset=rglobs('analytics/*')),
  ],
)

python_app(
  name='eng',
  binary='src/py/example/airflow/main',
  bundles=[
    bundle(fileset=rglobs('eng/*')),
  ],
)
